[env:esp32dev]
platform = espressif32@6.3.2
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
board_build.partitions = huge_app.csv

lib_deps =
    https://github.com/pschatzmann/arduino-audio-tools.git
    https://github.com/pschatzmann/arduino-libhelix.git
    https://github.com/pschatzmann/arduino-SAM.git
    https://github.com/earlephilhower/ESP8266Audio.git#1.9.7
    adafruit/Adafruit GFX Library
    adafruit/Adafruit SH110X
    bblanchon/ArduinoJson@^6.21.5

build_flags =
    -Wno-unused-variable
    -Wno-unused-function
    -Wno-unused-but-set-variable