[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps = 
    Marzogh/SPIMemory@^3.4.0
upload_port = COM3    ; change this
monitor_port = COM3   ; change this